### ISSUE TITLE
Feature : Visibility for entities

### ISSUE THREAD

**Issue by BlowaXD** [BlowaXD/ChickenAPI#11]
**Is your feature request related to a problem? Please describe.**
We should provide something that would permit to get an Entity visibility or to set it

**Describe the solution you'd like**
Based on what we know, we should approach two things :

`VisibilitySystem` 
should be a notifiable system (as on Nostale, the visibility is based on events)

`VisibilityComponent` 
should contain a boolean to set its own visibility

I'd suggest we also add some more options to that component for :
- A filter that will permit to Entity to be visible or not based on that filter (Family, Super Powers...)

**Additional context**
All infos i've got so far :

`in` packet is triggered :
Entity enters the map
Entity spawns (monsters/npcs)
Entity has super powers that permit to set its own visibility (GM)

`out` packet is triggered when :
Entity exit the map
Entity is killed / despawn
Entity has super powers that permit him to become invisibile (GM)

Scenarions to investigate : 
Invisibility on skill (as @friends111 said, it should cast a `su` packet)

**Comment by friends111** [comment]
> out packet is triggered when :
> Entity is killed / despawn

when the entity is killed in normal way, its removed with 'su' packet, there is argument which tells if the attacked is dead

> Entity cast an invisibility skill

there is a packet for invisibility, it does not out the entity, i think it was 'cl'

> in packet is triggered :
> Entity casted a invisibility skill and it timedout

also wrong, see before

**Comment by BlowaXD** [comment]
Incoming in the next sprint
