### ISSUE TITLE
Feature : Tick based server update

### ISSUE THREAD

**Issue by BlowaXD** [BlowaXD/ChickenAPI#23]
Systems should be updated on a tick basis (ENV/Config...)

**Comment by SylEze** [comment]
See: https://github.com/BlowaXD/ChickenAPI/commit/2565e032596a3bf4606501df6fdb28117e1bed74

First I separated system management from EntityManager.

It is a bit too expensive to update each system for each entities, so instead I have a SystemManager that update each of its systems. And each of these systems contain an EntityManager as member, then they can play with it to get the wanted entities.
