### ISSUE TITLE
Feature : movements

### ISSUE THREAD

**Issue by Elendan** [BlowaXD/ChickenAPI#29]
* [ ] Player movements
* [ ] Monster movements
* [ ] Npc's movements

**Comment by BlowaXD** [comment]
Player movements has to be handled with Walk Packet + MovableSystem

Monsters & Npcs movements have to be handled through movable system update on ticks

**Comment by Elendan** [comment]
Not all NPC's considering pets/partners (also considered as NPC, with the visualentity at least)

**Comment by SylEze** [comment]
Player movement must be a notifiable system.
Monster movement is a system which is called again and again while the map is active.
NPC movement is a little bit different, we need to gather informations for this.
If I remind well, the Mt Krem's guards are moving not too far from their initial position (4 or 5 cells), the only reason they move further is an enemy being carried by a player inside the city, the npc will attack him.
