### ISSUE TITLE
PACKET : AddobjPacket - addobj 

### ISSUE THREAD

**Issue by GodnessCookie** [BlowaXD/ChickenAPI#41]
# PacketName
addobj

## Packet Usage
This packet is sent when you add an object to your miniland

## Packet Header
`addobj`

## Packet Content
`{itemslot} {MapX} {MapY}`

## Few examples
`addobj 1 22 8` - adds the smallest warehouse to the map position X:31 Y:3 -> default position cant change x:22 y:8 is the the position where you click on the miniland map
`addobj 0 14 7 ` - adds the big warehouse to the map position x:31 Y:3 - see above
`addobj 3 21 22` - adds Lv3 Minigame (Stone thingy, dont know english name) to the map position X:21 Y:22

**Comment by BlowaXD** [comment]
solved in #40
