### ISSUE TITLE
PACKET : RmvobjPacket - rmvobj

### ISSUE THREAD

**Issue by GodnessCookie** [BlowaXD/ChickenAPI#42]
# PacketName
RmvobjPacket

## Packet Usage
This packet is sent when you remove an object from your miniland

## Packet Header
`rmvobj`

## Packet Content
`{slot}`

## Few examples
`rmvobj 3` Remove the object on slot 3
`rmvobj 2` Remove the object on slot 2 - nothing special

**Comment by BlowaXD** [comment]
solved in #40
