### ISSUE TITLE
PACKET : MviPacket - mvi

### ISSUE THREAD

**Issue by GodnessCookie** [BlowaXD/ChickenAPI#43]
# PacketName
Mvi

## Packet Usage
This packet is sent when moving items in your inventory

## Packet Header
`mvi`

## Packet Content
`{InventoryType} {InventorySlot} {Amout} {DestinationSlot}`

## Few examples
`mvi 0 0 1 1` - Moving an Item from Equiment Inventory Slot 1 to Slot 2
`mvi 1 6 100 7` - Moving a stackof 100 items from Main Inventory Slot 7 to 8

**Comment by BlowaXD** [comment]
solved in #40
