### ISSUE TITLE
PACKET : InvPacket - inv

### ISSUE THREAD

**Issue by GodnessCookie** [BlowaXD/ChickenAPI#44]
# PacketName
inv

## Packet Usage
This packet is sent AFTER moving items in your inventory. It is updating the visual part of the inventory.
The Packet for moving items is `mvi` #43

## Packet Header
`inv`

## Packet Content
`{InventoryType} {InventorySlot} {ItemVNum} {Rare} {Upgrade} {0}`

## Few examples
`mvi 0 0 1 1`
`ivn 0 1.349.7.10.0`- Move 1 Plexon 7+10 from Inv 1 slot 1 to 2
`ivn 0 0.-1.0.0.0` - not replacing anything

`mvi 0 0 1 1`
`ivn 0 1.349.7.10.0` - Move 1 Plexon 7+10 from Inv 1 slot 1 to 2 
`ivn 0 0.350.6.8.0` - replacing a Lv88 Sword 6+8

`mvi 1 0 100 1`
`ivn 1 1.1039.100.0`- Move 100 Tools for Swordsman from Inv 2 slot 1 to 2
`ivn 1 0.-1.0.0.0` - not replacing anything

`mvi 2 6 9 7`
`ivn 2 7.2024.9.0` - Move 9 Cookies from Inv 3 slot 7 to 8 
`ivn 2 6.2099.1.0` - Replacing 1 Red Fruit

**Comment by BlowaXD** [comment]
solved in #40
