### ISSUE TITLE
Review ECS performances

### ISSUE THREAD

**Issue by BlowaXD** [BlowaXD/ChickenAPI#59]
In many scenarios related to Nostale directly, an entity uses :
`VisualType` Type of the Entity
`Id` : This id depends on VisualType, Character and Monster can have the same Ids since their VisualType are different.

**Comment by SylEze** [comment]
I think ecs entities and whatever game entities (characters, npcs, or monsters) should be separated.

Instead we should think about a way to consider game entities as components of an ecs entity.

For example an **Entity** representing a **Player** can be the following:
**ClientComponent, CharacterComponent, FamilyComponent, PositionComponent, MessengerComponent,
InventoryComponent => Entity (Player)**

And an **Entity** representing a **NPC**:
**NpcComponent, PositionComponent, ShopComponent => Entity (NPC)**

**Comment by BlowaXD** [comment]
Shouldn't we consider that, actually, we do have 3 types of entities that might be separated and have properties to improve performance

`INpcEntity`
(*NpcComponent, PositionComponent, ShopComponent*) that should be stored into one single class with properties instead of being stored into a container (in our case, Dictionary)

`IPlayerEntity` : As its already done + those properties :
(*Session (ClientComponent or whatever its name, storing TCP & chickenAPI session)
Character (CharacterComponent)
Family (FamilyComponent) (considering that family is shared between players, we should share the component too, that's my idea)
Group (GroupComponent) (we should consider that GroupComponents can be shared between group members and some individual properties should be claimed instead of having each entity its component)
Position (PositionComponent), Messenger (storing friendlist/blacklist), Inventory, Battle)


`IMonsterEntity` : IEntity
NpcMonster (base stats, known as monster data)
Skills (SkillComponent)
Battle (BattleComponent)
Position (MovableComponent)


In that case, we will dodge the `GetComponent<T>()` overhead, since almost every system that have to update an entity call this method, we could simply, on knowledge basis, add some more properties to IEntities

**Comment by SylEze** [comment]
Why not keeping components container for ECS pattern integrity, and let the custom properties of each type of entities be a reference to an element of the container ? What do you think about that ?

**Comment by BlowaXD** [comment]
Does not break the ECS integrity, thats a good solution I think

**Comment by Eastrall** [comment]
This is a good idea. Using this process, you will describe your main entities during the compile time and still have the possibility to add or remove components at runtime.
By fetch a component every server tick will result in high CPU consumption, so I think declaring the components at compile time like you are planning it's a good solution.

Now, you can also think about common components. for exemple, create an `abstract` entity class that inherits from `IEntity` and give him a `ObjectComponent` or `CommonComponent` that will be common to every living entity in the world.

This will result in:
```cs
interface IEntity { }
abstract class EntityBase : IEntity { ... }

interface IPlayerEntity : IEntity { ... }
class PlayerEntity : EntityBase, IPlayerEntity { ... }

// And so on...
```

Keep going that way guys... :wink:

**Comment by BlowaXD** [comment]
Thanks for your feedback @Eastrall 
Yes, it's already done here : https://github.com/BlowaXD/ChickenAPI/blob/master/src/ChickenAPI/ECS/Entities/EntityBase.cs

This EntityBase is abstracted enough to be used somewhere else, not only on Nostale :)
