### ISSUE TITLE
PACKET : GetPacket - get

### ISSUE THREAD

**Issue by GodnessCookie** [BlowaXD/ChickenAPI#60]
# PacketName
get

## Packet Usage
This packet is sent when picking up a item.

## Packet Header
`get`

## Packet Content
`{1} {CharacterID} {DropID} {0}`

## Few examples
`get 1 1 100061 0` - picking up a item on the character with CharacterID1
`get 1 2 100062 0` - picking up a stack of 10 items on the character with CharacterID2

**Comment by BlowaXD** [comment]
fixed in #67
