### ISSUE TITLE
PACKET : PutPacket - put

### ISSUE THREAD

**Issue by GodnessCookie** [BlowaXD/ChickenAPI#61]
# PacketName
put

## Packet Usage
This packet is sent when dropping an item from your inventory on the ground.

## Packet Header
`put`

## Packet Content
`{InventoryType} {InventorySlot} {Amount}`

## Few examples
`put 1 2 1` - dropping 1 Smallpotion InventoryType 2 Slot 2 on the ground
`put 2 0 10` - dropping 10 cookies InventoryType 3 Slot 1 on the ground
`put 0 0 1` - dropping 1 Plexon InventoryType 1 Slot 1 on the ground

**Comment by BlowaXD** [comment]
fixed in #67
