### ISSUE TITLE
PACKET : WearPacket - wear

### ISSUE THREAD

**Issue by GodnessCookie** [BlowaXD/ChickenAPI#63]
# PacketName
wear

## Packet Usage
This packet is sent when equipping items. Only sent when equipping directly from InventoryType 1.

## Packet Header
`wear`

## Packet Content
`{InventorySlot} {WearType}`

## Few examples
`wear 0 0` - Equiping Plexon from Inventory Slot 1 -> Visible
`wear 0 1` - Equiping Plexon from Inventory Slot 1 -> Invisible (Not sure where the Item is, it does NOT affect the stats like this)
`wear 8 0` - Equiping Plexon from Inventory Slot 9 -> Visible

**Comment by BlowaXD** [comment]
fixed in #67
