### ISSUE TITLE
PACKET : BiPacket - b_i

### ISSUE THREAD

**Issue by GodnessCookie** [BlowaXD/ChickenAPI#66]
# PacketName
b_i

## Packet Usage
This packet is sent when you want to delte an item.

## Packet Header
`b_i`

## Packet Content
`{InventoryType} {InventorySlot}`

## Few examples
`b_i 2 3` - deleting an Item from Inventory Type 3 Slot 4
`b_i 1 3` - deleting an Item from Inventory Type 2 Slot 4

**Comment by BlowaXD** [comment]
fixed in #67
