### ISSUE TITLE
PACKET : PairyPacket - pairy

### ISSUE THREAD

**Issue by GodnessCookie** [BlowaXD/ChickenAPI#68]
# PacketName
pairy

## Packet Usage
This packet is sent when equipping or removing a fairy.

## Packet Header
`pairy`

## Packet Content
`{1} {CharacterId} {FairyMoveType} {ElementType} {FairyLevel} {ItemMorph}` 

## Few examples
`pairy 1 1 4 3 30 0` - equip 30% normal lightelement Fairy
`pairy 1 1 0 0 0 0` - remove fairy
`pairy 1 1 4 1 50 40` - equip 50%+ Nosmall fireelement Fairy

**Comment by BlowaXD** [comment]
fixed in #67
