### ISSUE TITLE
PACKET : UseSkillPacket

### ISSUE THREAD

**Issue by Clavss** [BlowaXD/ChickenAPI#80]
# PacketName
UseSkill

## Packet Usage
This packet is sent when a skill is used

## Packet Header
u_s

## Packet Content
**Sent by client:**
`u_s {CastId} {VisualType} {MapMonsterId} {MapX} {MapY}`

**VisualType:**
1 - players (heals/buffs)
2 - ?
3 - monsters (attacks)

## Few examples
`u_s 0 3 1868` (basic attack on a monster)
`u_s 14 1 483273` (buff on myself)
`u_s 4 1 483273 162 166` (dash on coord 162,166)

**Comment by BlowaXD** [comment]
It looks like the second body element is VisualType (3 = Monster and 1 = Player)

**Comment by Clavss** [comment]
Solved in #82
